// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ttnndev.Server.Data;

#nullable disable

namespace ttnndev.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724112318_WidenAnhDaiDien")]
    partial class WidenAnhDaiDien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("ttnndev.Server.Models.AuditLog", b =>
                {
                    b.Property<long>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MaLog"));

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("jsonb");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("jsonb");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("MaBatch")
                        .HasColumnType("integer");

                    b.Property<int?>("MaDoiTuong")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguoiThucHien")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaLog");

                    b.HasIndex("MaDoiTuong");

                    b.HasIndex("MaNguoiThucHien");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ttnndev.Server.Models.BoMon", b =>
                {
                    b.Property<int>("MaBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaBoMon"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaBoMon");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("TenBoMon")
                        .IsUnique();

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaCauHinh"));

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<short>("SoChuSoThapPhan")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ThangDiem")
                        .HasColumnType("numeric");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("MaLop");

                    b.ToTable("CauHinhDiemLop");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DeTai", b =>
                {
                    b.Property<int>("MaDeTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaDeTai"));

                    b.Property<bool>("KhoaChinhSua")
                        .HasColumnType("boolean");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaDeTai");

                    b.ToTable("DeTai");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DiemSinhVien", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("numeric");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaCotDiem")
                        .HasColumnType("integer");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaGhiDanh");

                    b.ToTable("DiemSinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.GhiDanhSinhVien", b =>
                {
                    b.Property<int>("MaGhiDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaGhiDanh"));

                    b.Property<string>("GhiDanhBang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDoDung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<int?>("MaLopChuyenTu")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayGhiDanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TinhTrangTienDo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrangThaiThucTap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaGhiDanh");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("GhiDanhSinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaKhoa");

                    b.HasIndex("TenKhoa")
                        .IsUnique();

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("ttnndev.Server.Models.KyThucTap", b =>
                {
                    b.Property<int>("MaKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaKy"));

                    b.Property<bool>("DaKhoaSoDiem")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaKhoaVinhVien")
                        .HasColumnType("boolean");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("KhoaBoi")
                        .HasColumnType("integer");

                    b.Property<string>("LoaiThucTap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaGiaoVuTao")
                        .HasColumnType("integer");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("NgayKhoaSoDiem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayKhoaSoDiemThucTe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("SoNgayCanhBaoSom")
                        .HasColumnType("smallint");

                    b.Property<string>("TenKy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaKy");

                    b.HasIndex("LoaiThucTap", "HocKy", "NamHoc", "MaKhoa")
                        .IsUnique();

                    b.ToTable("KyThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("GiangVienId")
                        .HasColumnType("integer");

                    b.Property<string>("LinkMeeting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianHop")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LichSuImport", b =>
                {
                    b.Property<int>("MaBatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaBatch"));

                    b.Property<int?>("MaLop")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguoiThucHien")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoGhiDe")
                        .HasColumnType("integer");

                    b.Property<int>("SoHopLe")
                        .HasColumnType("integer");

                    b.Property<int>("SoLoi")
                        .HasColumnType("integer");

                    b.Property<string>("VaiTroImport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaBatch");

                    b.HasIndex("MaNguoiThucHien");

                    b.ToTable("LichSuImport");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaLop"));

                    b.Property<bool>("GhiDanhMo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("HanGhiDanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KhoaDangKyBoi")
                        .HasColumnType("integer");

                    b.Property<string>("LinkHopMacDinh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaKy")
                        .HasColumnType("integer");

                    b.Property<string>("MaThamGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("MoDangKyDeTaiCapLop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NgayKhoaDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoThuTuLop")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKy");

                    b.ToTable("LopThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<bool>("BuocDoiMatKhau")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("KhoaDangNhapDenLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MatKhauHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("SoLanDangNhapSai")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("TokenValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaDinhDanh")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhatKy", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("CongViecDaLam")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KeHoachTuanToi")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KhoKhan")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NhanXetGiangVien")
                        .HasColumnType("text");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tuan")
                        .HasColumnType("integer");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaGhiDanh");

                    b.ToTable("NhatKy");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhomDiem", b =>
                {
                    b.Property<int>("MaNhomDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaNhomDiem"));

                    b.Property<int?>("CauHinhDiemLopMaCauHinh")
                        .HasColumnType("integer");

                    b.Property<int>("MaCauHinh")
                        .HasColumnType("integer");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNhomDiem");

                    b.HasIndex("CauHinhDiemLopMaCauHinh");

                    b.ToTable("NhomDiem");
                });

            modelBuilder.Entity("ttnndev.Server.Models.PhienChat", b =>
                {
                    b.Property<long>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MaPhien"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhien");

                    b.ToTable("PhienChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.QuyenGiaoVu", b =>
                {
                    b.Property<int>("MaQuyenGiaoVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaQuyenGiaoVu"));

                    b.Property<int>("CapBoiGanNhat")
                        .HasColumnType("integer");

                    b.Property<int>("MaGiaoVu")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayCapGanNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("QuyenQuanLyNguoiDung")
                        .HasColumnType("boolean");

                    b.HasKey("MaQuyenGiaoVu");

                    b.HasIndex("MaGiaoVu")
                        .IsUnique();

                    b.ToTable("QuyenGiaoVu");
                });

            modelBuilder.Entity("ttnndev.Server.Models.RefreshToken", b =>
                {
                    b.Property<long>("MaRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MaRefreshToken"));

                    b.Property<bool>("DaThuHoi")
                        .HasColumnType("boolean");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ThoiDiemHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ThoiDiemTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MaRefreshToken");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiTaiLenId")
                        .HasColumnType("integer");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrangThaiAn")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaiLenId");

                    b.ToTable("TaiLieus");
                });

            modelBuilder.Entity("ttnndev.Server.Models.ThongTinCanBo", b =>
                {
                    b.Property<int>("MaThongTinCanBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaThongTinCanBo"));

                    b.Property<int?>("MaBoMon")
                        .HasColumnType("integer");

                    b.Property<int>("MaCanBo")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.HasKey("MaThongTinCanBo");

                    b.HasIndex("MaBoMon");

                    b.HasIndex("MaCanBo")
                        .IsUnique();

                    b.HasIndex("MaKhoa");

                    b.ToTable("ThongTinCanBo");
                });

            modelBuilder.Entity("ttnndev.Server.Models.ThongTinSinhVien", b =>
                {
                    b.Property<int>("MaThongTinSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaThongTinSinhVien"));

                    b.Property<string>("LopSinhHoat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.HasKey("MaThongTinSinhVien");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaSinhVien")
                        .IsUnique();

                    b.ToTable("ThongTinSinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TieuChiRubric", b =>
                {
                    b.Property<int>("MaTieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaTieuChi"));

                    b.Property<int>("MaRubric")
                        .HasColumnType("integer");

                    b.Property<string>("TenTieuChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTieuChi");

                    b.ToTable("TieuChiRubric");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TinNhanChat", b =>
                {
                    b.Property<long>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("MaTinNhan"));

                    b.Property<string>("LinkThamChieu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("MaPhien")
                        .HasColumnType("bigint");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaiTroGui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaPhien");

                    b.ToTable("TinNhanChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.YeuCauTaiKhoan", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaYeuCau"));

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LyDoYeuCau")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaBatch")
                        .HasColumnType("integer");

                    b.Property<int?>("MaDoiTuong")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNguoiXuLy")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguoiYeuCau")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("MaDoiTuong");

                    b.HasIndex("MaNguoiXuLy");

                    b.HasIndex("MaNguoiYeuCau");

                    b.ToTable("YeuCauTaiKhoan");
                });

            modelBuilder.Entity("ttnndev.Server.Models.YeuCauXacThuc", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("MaYeuCau"));

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiYeuCau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ThoiDiemHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ThoiDiemTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("YeuCauXacThuc");
                });

            modelBuilder.Entity("ttnndev.Server.Models.AuditLog", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("MaDoiTuong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("MaNguoiThucHien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoiTuong");

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.BoMon", b =>
                {
                    b.HasOne("ttnndev.Server.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.HasOne("ttnndev.Server.Models.LopThucTap", "LopThucTap")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DiemSinhVien", b =>
                {
                    b.HasOne("ttnndev.Server.Models.GhiDanhSinhVien", "GhiDanh")
                        .WithMany()
                        .HasForeignKey("MaGhiDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GhiDanh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.GhiDanhSinhVien", b =>
                {
                    b.HasOne("ttnndev.Server.Models.LopThucTap", "LopThucTap")
                        .WithMany("DanhSachGhiDanh")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopThucTap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LichHen", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LichSuImport", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("MaNguoiThucHien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.KyThucTap", "KyThucTap")
                        .WithMany()
                        .HasForeignKey("MaKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KyThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhatKy", b =>
                {
                    b.HasOne("ttnndev.Server.Models.GhiDanhSinhVien", "GhiDanh")
                        .WithMany()
                        .HasForeignKey("MaGhiDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GhiDanh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhomDiem", b =>
                {
                    b.HasOne("ttnndev.Server.Models.CauHinhDiemLop", null)
                        .WithMany("NhomDiems")
                        .HasForeignKey("CauHinhDiemLopMaCauHinh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.QuyenGiaoVu", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "GiaoVu")
                        .WithMany()
                        .HasForeignKey("MaGiaoVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVu");
                });

            modelBuilder.Entity("ttnndev.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TaiLieu", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiTaiLen")
                        .WithMany()
                        .HasForeignKey("NguoiTaiLenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTaiLen");
                });

            modelBuilder.Entity("ttnndev.Server.Models.ThongTinCanBo", b =>
                {
                    b.HasOne("ttnndev.Server.Models.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("MaBoMon");

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "CanBo")
                        .WithMany()
                        .HasForeignKey("MaCanBo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");

                    b.Navigation("CanBo");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("ttnndev.Server.Models.ThongTinSinhVien", b =>
                {
                    b.HasOne("ttnndev.Server.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TinNhanChat", b =>
                {
                    b.HasOne("ttnndev.Server.Models.PhienChat", "PhienChat")
                        .WithMany()
                        .HasForeignKey("MaPhien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhienChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.YeuCauTaiKhoan", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "DoiTuong")
                        .WithMany()
                        .HasForeignKey("MaDoiTuong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("MaNguoiXuLy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiYeuCau")
                        .WithMany()
                        .HasForeignKey("MaNguoiYeuCau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoiTuong");

                    b.Navigation("NguoiXuLy");

                    b.Navigation("NguoiYeuCau");
                });

            modelBuilder.Entity("ttnndev.Server.Models.YeuCauXacThuc", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.Navigation("NhomDiems");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.Navigation("DanhSachGhiDanh");
                });
#pragma warning restore 612, 618
        }
    }
}
