// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ttnndev.Server.Data;

#nullable disable

namespace ttnndev.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.Property<int>("MaCauHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCauHinh"));

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<short>("SoChuSoThapPhan")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ThangDiem")
                        .HasColumnType("numeric");

                    b.HasKey("MaCauHinh");

                    b.HasIndex("MaLop");

                    b.ToTable("CauHinhDiemLop");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DeTai", b =>
                {
                    b.Property<int>("MaDeTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDeTai"));

                    b.Property<bool>("KhoaChinhSua")
                        .HasColumnType("boolean");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaDeTai");

                    b.ToTable("DeTai");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DiemSinhVien", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDiem"));

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("numeric");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaCotDiem")
                        .HasColumnType("integer");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaGhiDanh");

                    b.ToTable("DiemSinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.GhiDanhSinhVien", b =>
                {
                    b.Property<int>("MaGhiDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGhiDanh"));

                    b.Property<string>("GhiDanhBang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LyDoDung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaLop")
                        .HasColumnType("integer");

                    b.Property<int?>("MaLopChuyenTu")
                        .HasColumnType("integer");

                    b.Property<int>("MaSinhVien")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayDung")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayGhiDanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TinhTrangTienDo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrangThaiThucTap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaGhiDanh");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaSinhVien", "MaLop")
                        .IsUnique();

                    b.ToTable("GhiDanhSinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.KyThucTap", b =>
                {
                    b.Property<int>("MaKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKy"));

                    b.Property<bool>("DaKhoaSoDiem")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaKhoaVinhVien")
                        .HasColumnType("boolean");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("KhoaBoi")
                        .HasColumnType("integer");

                    b.Property<int>("MaGiaoVuTao")
                        .HasColumnType("integer");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("integer");

                    b.Property<int>("MaLoaiThucTap")
                        .HasColumnType("integer");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayKhoaSoDiem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NgayKhoaSoDiemThucTe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("SoNgayCanhBaoSom")
                        .HasColumnType("smallint");

                    b.Property<string>("TrangThaiCongBo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TrangThaiKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaKy");

                    b.ToTable("KyThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLop"));

                    b.Property<bool>("GhiDanhMo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("HanGhiDanh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KhoaDangKyBoi")
                        .HasColumnType("integer");

                    b.Property<string>("LinkHopMacDinh")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("integer");

                    b.Property<int>("MaKy")
                        .HasColumnType("integer");

                    b.Property<string>("MaThamGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("MoDangKyDeTaiCapLop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("NgayKhoaDangKy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoThuTuLop")
                        .HasColumnType("integer");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKy");

                    b.ToTable("LopThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("BuocDoiMatKhau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("KhoaDangNhapDenLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MatKhauHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("NgayXoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("SoLanDangNhapSai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTimeOffset>("TokenValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThaiTaiKhoan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Nhap");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaDinhDanh")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhatKy", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("CongViecDaLam")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KeHoachTuanToi")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("KhoKhan")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MaGhiDanh")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NhanXetGiangVien")
                        .HasColumnType("text");

                    b.Property<string>("TrangThaiDuyet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tuan")
                        .HasColumnType("integer");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaGhiDanh");

                    b.ToTable("NhatKy");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhomDiem", b =>
                {
                    b.Property<int>("MaNhomDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhomDiem"));

                    b.Property<int?>("CauHinhDiemLopMaCauHinh")
                        .HasColumnType("integer");

                    b.Property<int>("MaCauHinh")
                        .HasColumnType("integer");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNhomDiem");

                    b.HasIndex("CauHinhDiemLopMaCauHinh");

                    b.ToTable("NhomDiem");
                });

            modelBuilder.Entity("ttnndev.Server.Models.PhienChat", b =>
                {
                    b.Property<long>("MaPhien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaPhien"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaPhien");

                    b.ToTable("PhienChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TieuChiRubric", b =>
                {
                    b.Property<int>("MaTieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTieuChi"));

                    b.Property<int>("MaRubric")
                        .HasColumnType("integer");

                    b.Property<string>("TenTieuChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaTieuChi");

                    b.ToTable("TieuChiRubric");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TinNhanChat", b =>
                {
                    b.Property<long>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaTinNhan"));

                    b.Property<string>("LinkThamChieu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("MaPhien")
                        .HasColumnType("bigint");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ThoiDiem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaiTroGui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaPhien");

                    b.ToTable("TinNhanChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.HasOne("ttnndev.Server.Models.LopThucTap", "LopThucTap")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.DiemSinhVien", b =>
                {
                    b.HasOne("ttnndev.Server.Models.GhiDanhSinhVien", "GhiDanh")
                        .WithMany()
                        .HasForeignKey("MaGhiDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GhiDanh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.GhiDanhSinhVien", b =>
                {
                    b.HasOne("ttnndev.Server.Models.LopThucTap", "LopThucTap")
                        .WithMany("DanhSachGhiDanh")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.NguoiDung", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopThucTap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.HasOne("ttnndev.Server.Models.NguoiDung", "GiangVien")
                        .WithMany()
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ttnndev.Server.Models.KyThucTap", "KyThucTap")
                        .WithMany("LopThucTaps")
                        .HasForeignKey("MaKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("KyThucTap");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhatKy", b =>
                {
                    b.HasOne("ttnndev.Server.Models.GhiDanhSinhVien", "GhiDanh")
                        .WithMany()
                        .HasForeignKey("MaGhiDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GhiDanh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.NhomDiem", b =>
                {
                    b.HasOne("ttnndev.Server.Models.CauHinhDiemLop", null)
                        .WithMany("NhomDiems")
                        .HasForeignKey("CauHinhDiemLopMaCauHinh");
                });

            modelBuilder.Entity("ttnndev.Server.Models.TinNhanChat", b =>
                {
                    b.HasOne("ttnndev.Server.Models.PhienChat", "PhienChat")
                        .WithMany()
                        .HasForeignKey("MaPhien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhienChat");
                });

            modelBuilder.Entity("ttnndev.Server.Models.CauHinhDiemLop", b =>
                {
                    b.Navigation("NhomDiems");
                });

            modelBuilder.Entity("ttnndev.Server.Models.KyThucTap", b =>
                {
                    b.Navigation("LopThucTaps");
                });

            modelBuilder.Entity("ttnndev.Server.Models.LopThucTap", b =>
                {
                    b.Navigation("DanhSachGhiDanh");
                });
#pragma warning restore 612, 618
        }
    }
}
